### ISSUE TITLE
Need a feature to export/import story map

### ISSUE THREAD

**Issue by lzhshen** [amborle/featmap#25]
Currently, there is a way to export story map as csv file. 
I did not find any way to import the file to another featmap system.

**Comment by lockered** [comment]
Because I am using the system like a local application, such a feature would be nice.
As an idea: 
The communication between backend and frontend is done via JSON. So it should be relatively easy to offer an export of a project as a JSON-File.   
An import should then translate the JSON-Elements into API-Calls to write the complete object structure. Because of the usage of uuids as ids a clash of ids should not happen.

**Comment by amborle** [comment]
Hi @lzhshen, since this is an improvement idea - can you please create an issue here: https://github.com/amborle/featmap/discussions/categories/ideas
